
# Source: alidns-webhook/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alidns
  labels:
    app: alidns
    chart: alidns-webhook-0.1.0
    release: plundering-deer
    heritage: Tiller
---
# Source: alidns-webhook/templates/rbac.yaml
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: alidns:domain-solver
  labels:
    app: alidns
    chart: alidns-webhook-0.1.0
    release: plundering-deer
    heritage: Tiller
rules:
  - apiGroups:
      - acme.lihuaio.com
    resources:
      - '*'
    verbs:
      - 'create'
---
# Source: alidns-webhook/templates/rbac.yaml
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: alidns:auth-delegator
  labels:
    app: alidns
    chart: alidns-webhook-0.1.0
    release: plundering-deer
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: alidns
    namespace: default
---
# Source: alidns-webhook/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: alidns:domain-solver
  labels:
    app: alidns
    chart: alidns-webhook-0.1.0
    release: plundering-deer
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alidns:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
# Source: alidns-webhook/templates/rbac.yaml
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: alidns:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: alidns
    chart: alidns-webhook-0.1.0
    release: plundering-deer
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: alidns
    namespace: default
---
# Source: alidns-webhook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: alidns
  labels:
    app: alidns
    chart: alidns-webhook-0.1.0
    release: plundering-deer
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: alidns
    release: plundering-deer
---
# Source: alidns-webhook/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: alidns
  labels:
    app: alidns
    chart: alidns-webhook-0.1.0
    release: plundering-deer
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alidns
      release: plundering-deer
  template:
    metadata:
      labels:
        app: alidns
        release: plundering-deer
    spec:
      serviceAccountName: alidns
      containers:
        - name: alidns-webhook
          image: "tttlkkkl/cert-manage-alidns:latest"
          imagePullPolicy: Always
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "acme.lihuaio.com"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
            
      volumes:
        - name: certs
          secret:
            secretName: alidns-webhook-tls
---
# Source: alidns-webhook/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.acme.lihuaio.com
  labels:
    app: alidns
    chart: alidns-webhook-0.1.0
    release: plundering-deer
    heritage: Tiller
  annotations:
    certmanager.k8s.io/inject-ca-from: "default/alidns-webhook-tls"
spec:
  group: acme.lihuaio.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: alidns
    namespace: default
  version: v1alpha1
---
# Source: alidns-webhook/templates/pki.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: alidns-ca
  namespace: "default"
  labels:
    app: alidns
    chart: alidns-webhook-0.1.0
    release: plundering-deer
    heritage: Tiller
spec:
  secretName: alidns-ca
  duration: 43800h # 5y
  issuerRef:
    name: alidns-selfsign
  commonName: "ca.alidns-webhook.cert-manager"
  isCA: true
---
# Source: alidns-webhook/templates/pki.yaml
# Finally, generate a serving certificate for the webhook to use
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: alidns-webhook-tls
  namespace: "default"
  labels:
    app: alidns
    chart: alidns-webhook-0.1.0
    release: plundering-deer
    heritage: Tiller
spec:
  secretName: alidns-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: alidns-ca
  dnsNames:
  - alidns
  - alidns.default
  - alidns.default.svc
---
# Source: alidns-webhook/templates/pki.yaml
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: alidns-selfsign
  namespace: "default"
  labels:
    app: alidns
    chart: alidns-webhook-0.1.0
    release: plundering-deer
    heritage: Tiller
spec:
  selfSigned: {}
---
# Source: alidns-webhook/templates/pki.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: alidns-ca
  namespace: "default"
  labels:
    app: alidns
    chart: alidns-webhook-0.1.0
    release: plundering-deer
    heritage: Tiller
spec:
  ca:
    secretName: alidns-ca
