#RBAC
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: alidns:secret-reader
rules:
  - apiGroups:
      - ''
    resources:
      - 'secrets'
    resourceNames:
      - 'alibaba-api-dns-secret'
    verbs:
      - 'get'
      - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: alidns:secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alidns:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: alidns
    namespace: cert-manager
---
# ClusterIssuer
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tttlkkkl@aliyun.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: 
        dnsNames:
        - '*.lihuaio.com'
      dns01:
        webhook:
          config:
            accessKeyRef:
              accessKeySecretKey: accessKeySecret
              accessKeyIdKey: accessKeyId
              name: alibaba-api-dns-secret
            regionId: "cn-shenzhen"
            ttl: 600
          groupName: acme.lihuaio.com

---
#Certificate
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: lihuaio.com
  namespace: default
spec:
  secretName: lihuaio.com
  commonName: '*.lihuaio.com'
  dnsNames:
  - "*.lihuaio.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
#igress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik 
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
  name: nginx-ingress
spec:
  rules:
    - host: "xx.lihuaio.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: li
              servicePort: 80
  tls:
    - hosts:
        - '*.lihuaio.com'
      secretName: lihuaio.com
---
# nginx -- hello word
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-hello-word
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-hello-word
    spec:
      containers:
      - name: nginx-hello-word
        image: nginx:1.17.3-alpine
---
# nginx hello word service
kind: Service
apiVersion: v1
metadata:
  name:  nginx-hello-word
spec:
  selector:
    app:  svc-nginx-hello-word
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  80